[package]
name = "probe-test-macro"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
usdt = { path = "../usdt", default-features = false }

[build-dependencies]
version_check = "0.9.5"

[features]
default = ["asm"]
asm = ["usdt/asm"]
