[package]
name = "probe-test-macro"
version = "0.1.0"
authors = ["Benjamin Naecker <ben@oxidecomputer.com>",
           "Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2018"

[dependencies]
usdt = { path = "../usdt" }

[features]
asm = ["usdt/asm"]
no-linker = ["usdt/no-linker"]
