[package]
name = "probe-test-build"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
usdt = { path = "../usdt", default-features = false }

[build-dependencies]
usdt = { path = "../usdt" }
